stages:
  - lint_and_test
  - publish

lint_and_test:
  stage: lint_and_test
  image: node:20
  script:
    - cd server
    - npm install
    - npm run lint
    - npm run test
    - cd ..
    - cd client
    - npm install --legacy-peer-deps
    - npm run lint
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "develop"'
      when: always

publish:
  stage: publish
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$PAT" | docker login "$REGISTRY" -u "$GITLAB_USER_LOGIN" --password-stdin
  script:
    - docker build ./client --file ./client/Dockerfile --tag "$REGISTRY/$PROJECT_PATH/or1on-client:latest"
    - docker push "$REGISTRY/$PROJECT_PATH/or1on-client:latest"

    - docker build ./server --file ./server/Dockerfile --tag "$REGISTRY/$PROJECT_PATH/or1on-server:latest"
    - docker push "$REGISTRY/$PROJECT_PATH/or1on-server:latest"

    - docker pull postgres:latest
    - docker tag postgres:latest "$REGISTRY/$PROJECT_PATH/postgres:latest"
    - docker push "$REGISTRY/$PROJECT_PATH/postgres:latest"

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
